### PR TITLE
feat: add mutation and e2e tests

### PR DESCRIPTION
**Pull request by drewterry**
Adds e2e tests to plugin-template.

I had to add a mutation to create `example` entities in order to test.  In the interest of creating a good starting point for others, I add this mutation to a new `adminApiExtension`.

The tests will add an example, check that it exists in the admin api, and then check that it exists in the shop api.

(This will conflict with the dev server PR, so I will update whichever one gets merged second)

### CODE REVIEW

**Comment by michaelbromley** [comment]
🥳 Just merged the other one so once you update this, I'll merge this one too!

**Comment by drewterry** [comment]
@michaelbromley updated!

**Comment by michaelbromley** [comment]
Thanks! BTW do you have any plans to add the codegen too?

**Comment by drewterry** [comment]
Yep! Working on it now, but I keep running into the error I just posted in the slack channel.  It seems to happen when I add npm packages, and try to rebuild the docker containers.  🤔

**Pull request merged**
